<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>ddd11f61-ae6e-48df-bf07-a56fc19c9faf</UserSecretsId>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WeddingRsvp.Api\WeddingRsvp.Api.csproj" />
      <ProjectReference Include="..\WeddingRsvp.WebApp\WeddingRsvp.WebApp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.0.0" />
    </ItemGroup>

</Project>
